### ISSUE TITLE
Token pool page showing transfers for tokens in other pools

### ISSUE THREAD

**Issue by mkashgarian** [hyperledger/firefly-ui#100]
Tokens -> Token pools -> click into a token pool. This page shows a list of token transfers but is showing tokens that are not in the current token pool. See screenshots below where a token pool created at 4:50pm has tokens listed that were created earlier.

![image](https://user-images.githubusercontent.com/11747966/153506702-066d0c89-d9ef-45d6-a366-aea7365e49f9.png)

![image](https://user-images.githubusercontent.com/11747966/153506664-86c44e57-2005-47d2-91a5-dc4e2bb2e295.png)

**Comment by awrichar** [comment]
This page is attempting to filter transfers by "poolprotocolid":
https://github.com/hyperledger/firefly-ui/blob/8cb358c5d1a000cbb7bc3c87a7039f4234ea347b/src/modules/tokens/views/TokenPools/TokenPoolDetails.tsx#L117

This filter was replaced with a "pool" filter instead, which uses the pool ID (not the protocol ID):
https://github.com/hyperledger/firefly/commit/72549d0053e3d52b629ccac48181888a7f337afd

**Comment by eberger727** [comment]
New UI resolves this issue
