### ISSUE TITLE
UI Activity Section - Timeline

### ISSUE THREAD

**Issue by shorsher** [hyperledger/firefly-ui#104]
- [ ] Timeline

<img width="1440" alt="Screen Shot 2022-02-17 at 3 26 53 PM" src="https://user-images.githubusercontent.com/10987380/154565200-cdc0f0e9-2548-4082-875d-2ababe210d70.png">
<img width="1439" alt="Screen Shot 2022-02-17 at 3 27 06 PM" src="https://user-images.githubusercontent.com/10987380/154565204-7a489b23-2c10-4e5e-bff6-f867dcf287b6.png">

**Comment by shorsher** [comment]
Ongoing work items: https://github.com/hyperledger/firefly-ui/issues/102

**Comment by eberger727** [comment]
Tracking broader issue in #106
