### ISSUE TITLE
Downloading blob for non-default namespace fails

### ISSUE THREAD

**Issue by gabriel-indik** [hyperledger/firefly-ui#185]
Steps to reproduce:
 - Upload a blob to a custom namespace.
 - In the UI navigate to "Off-chain" -> "Data". Click on the "Download" icon. A file will be downloaded. The content of that file will be a FF error code: `{"error":"FF10143: No result found"}`

**Comment by shorsher** [comment]
I believe this was resolved in https://github.com/hyperledger/firefly-ui/pull/194
