### ISSUE TITLE
Fix horizontal scrollbar on dashboard "latest messages" table

### ISSUE THREAD

**Issue by shorsher** [hyperledger/firefly-ui#54]
On smaller screen sizes, the `DataTable` will introduce horizontal scrolling. This is most noticeable in the "latest messages" table on the dashboard. I think a good solution is possibly  adjusting `minWidth`/`maxWidth` on the `DataTable` cells + hiding columns when the screen reaches certain media checkpoints, using the `useMediaQuery` material-ui hook (https://material-ui.com/components/use-media-query/)

<img width="509" alt="Screen Shot 2021-08-31 at 3 33 35 PM" src="https://user-images.githubusercontent.com/10987380/131564752-d8c60a9c-7260-4df8-84c3-39619f1b3af3.png">

**Comment by mahnoormmalik** [comment]
Hi, can I work on this issue as part of the GHC open source day?

**Comment by shorsher** [comment]
Hey @mahnoormmalik, absolutely! If you have any questions, I'm in the firefly hyperledger rocketchat under `shorsher`.

**Comment by shorsher** [comment]
@mahnoormmalik, as an example, in `Dashboard.tsx` I believe you could use `useMediaQuery` like so:

I think `author` and `type` should be the columns that are always displayed

```
// create medium screen breakpoint
const isSmall = useMediaQuery(theme.breakpoints.down('md'));

// columns that are always displayed
const messageColumnHeaders = [
  t('author'),
  t('type'),
];

//push optional columns on larger screens
if (!isSmall) messageColumnsHeaders.push(
    t('dataHash'),
    t('createdOn'),
)
```

You would need to do something similar when creating the rows themselves that is the variable `messageRecords`. https://github.com/hyperledger/firefly-ui/blob/main/src/views/Dashboard.tsx#L132
