### ISSUE TITLE
Message Details view shows all data from the batch, not just the selected message

### ISSUE THREAD

**Issue by awrichar** [hyperledger/firefly-ui#91]
When viewing a Message, the UI should show the data item(s) that were attached to that message only. Currently, it appears to query the Batch ID from the Message, and then display all data items from that Batch.

https://github.com/hyperledger/firefly-ui/blob/30b31a0a046b6a4c7c5fe19963fb1644586847ec/src/modules/data/views/Messages/MessageDetails.tsx#L240

**Comment by eberger727** [comment]
#129
