### ISSUE TITLE
Protocol ID Overflows on page

### ISSUE THREAD

**Issue by eberger727** [hyperledger/firefly-ui#99]
The https://github.com/hyperledger/firefly-tokens-erc20-erc721/ token connector generates long Pool IDs. This causes the pool ID to run off the page sometimes. This can be fixed by extracting and displaying just the `standard` or `address` field from the PoolID. The community should decide what makes most sense to show here.

![image](https://user-images.githubusercontent.com/17093033/152248520-4df483b8-c323-4aa3-9b3c-d77fa5ca5413.png)
![image](https://user-images.githubusercontent.com/17093033/152248545-e38b5cdf-a017-4ed5-b8fe-c587de1baa2c.png)

**Comment by awrichar** [comment]
I'm not sure the UI should do any parsing of the protocol ID, as it's completely up to the connector implementation to decide the formatting. I think we should just elide if it's too long.

**Comment by eberger727** [comment]
New UI resolves this issue
